language: python
cache: pip
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: required

install: 'pip install -e .'
before_script:
  - pip install flake8 pytest
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics

# command to run tests
script: pytest
